

export const demoMessages = {
  messageLogin: "Logging in as guest",
  messageShowViews: "The daytimer view can be switched between day, weekday and full week modes using the buttons at the top left of the calendar.",
  messageBegin: "The automated demo will begin in a few seconds",
  messageReady: "This will begin an automated walk-through. Please avoid using your mouse or keyboard during the demo. Click Next when ready.",
  messageComplete: "This completes the demo. More information will be added as development continues. Thank you for your attention.",
  messageListToggle: "To hide or show the event calendar, click the X icon in the sidebar like this.",
  messageToggle: "However if you want more space, the event list can be hidden using the X icon in the sidebar", 
  messageSearch: "You can search for events by using the provided input bar which displays event details including the date, room name and the name of the event creator.",
  messageHome: "This is the home page. It shows all events for the current date by default.",
  messageEventEdit: "The event form allows the editing of individual events in your facility. Notice that the event list is still visible in the left panel to allow continuous editing without returning to the main list",
  messageReset: "Once editing is complete, the full event list can be reopened by using the back button on the sidebar",
  messageRoomEdit: "By clicking the room name like I am doing now, Rooms can be edited without losing your place in the list . Now is that cool or what!",
  messageRoomDemo: "For example, the room list can be opened by clicking the Rooms button in the sidebar like so.",
  messagePause: "Although the event list is the main page of the application. Other pages can be reached using the sidebar controls",
  messageWelcome: "This is an automated demo. I will control your screen while showing you the features of the new EventBuilder version 8. Sit back relax and I will do all the work.",
  messageDateDemo: "Dates can be changed using the inline calendar, like this.",
  messageEventDemo: "Open an event for editing by clicking on any event name.", 
  messageDaytimerShowing: "You can open and close columns by clicking on the room name in any column header",
  messageColumnMenu: "There is also a column menu to select columns to show only the rooms you are interested in.",
  messageDaytimer: "There is also a daytimer view that shows events in an easy to read grid",
  drawerComplete: "Next: Logging off",
  drawerWelcome: "Next: Using the home page",
  drawerBack: "Next: Returning to the main list",
  drawerForm: "Next: Editing selected events",
  drawerRoom: "Next: Using the roomlist",
  drawerHome: "Next: Using the calendar",
  drawerSearch: "Next: The event search bar",

  step1: "Welcome",
  step2: "Using the home page",
  step3: "Finding events",
  step4: "Working with rooms",
  step5: "Editing events",
  step6: "Returning home",
  step7: "Conclusion",
}
 

export const demoLanguages = {
  // Arabic: 'ar-SA',
  // Armenian: 'hy-AM',
  // Croatian: 'hr-HR',
  // Czech: 'cs-CZ',
  Danish: 'da-DK',
  Dutch: 'nl-NL',
  French: 'fr-FR',
  German: 'de-DE',
  // Greek: 'el-GR', 
  // Hebrew: 'he-IL',
  // Indonesian: 'id-ID',
  // Irish: 'ga-IE',
  Italian: 'it-IT',
  Japanese: 'ja-JP',
  // Latin: 'la',
  // Latvian: 'lv-LV',
  // Lithuanian: 'lt-LT',
  // Mongolian: 'mn-MN',
  // Pashto: 'ps-AF',
  // Persian: 'fa-IR',
  // Polish: 'pl-PL',
  'Portuguese (Portugal, Brazil)': 'pt-PT',
  // Romanian: 'ro-RO',
  // Russian: 'ru-RU', 
  // Serbian: 'sr-RS',
  // Sesotho: 'st-ZA',
  Spanish: 'es-ES',
};



// const demoLanguages = {
//   Arabic: 'ar',
//   Armenian: 'hy',
//   Croatian: 'hr',
//   Czech: 'cs',
//   Danish: 'da',
//   Dutch: 'nl',
//   French: 'fr',
//   German: 'de',
//   Greek: 'el', 
//   Hebrew: 'he',
//   Indonesian: 'id',
//   Irish: 'ga',
//   Italian: 'it',
//   Japanese: 'ja',
//   Latin: 'la',
//   Latvian: 'lv',
//   Lithuanian: 'lt',
//   Mongolian: 'mn',
//   Pashto: 'ps',
//   Persian: 'fa',
//   Polish: 'pl',
//   'Portuguese (Portugal, Brazil)': 'pt',
//   Romanian: 'ro',
//   Russian: 'ru', 
//   Serbian: 'sr',
//   Sesotho: 'st',
//   Spanish: 'es',
// };
